import { IPagination } from "../../../config/axios/axios-interface";

export interface IUserPost {
  id: string | number;
  name: string;
  email: string;
  password: string;
  img?: string;
  tel: string;
  position?: number;
  positionId?: number;
  firstname?: string;
  lastname?: string;
}

export interface IUserColumnType extends Omit<IUser, "password"> {
  createAt: string;
  firstName: string;
  lastName: string;
  positionId: number;
  position: number;
}

export interface IUserSearch {
  email: string;
  name: string;
  tel: string;
  status?: string;
}

export interface IUserUpdatePassword {
  id: string | number;
  oldpassword: string;
  password: string;
}
// Generated by https://quicktype.io

export interface IUserResult {
  data: IUser[];
  count: number;
  page: number;
  limit: number;
  pageCount: number;
}

export interface IUser extends IPagination {
  id: number;
  name: string;
  email: string;
  password: string;
  img?: string;
  tel: string;
  positionId?: number;
  createAt?: string;
  deleteAt?: null;
  UpdateAt?: string;
  schedule?: any[];
  position?: Position | number;
}

export interface IUserUpdate {
  id?: number;
  name: string;
  email: string;
  password?: string;
  img?: string;
  tel: string;
  position?: number | unknown;
  createAt?: string;
  deleteAt?: null;
  UpdateAt?: string;
}

export interface Position {
  id: number;
  position: string;
  createAt: string;
  deleteAt: null;
  UpdateAt: string;
}
